Summary:
Add expectThrows utility to LuceneTestCase
Description:
In junit5, a neat assertion method is added which makes testing expected
failures a little more straightforward. The block of code that is
expected to throw is passed in with a lambda expression, and the caught
exception returned for inspection. The usage looks something like this:
IOException e = expectThrows(IOException.class, () -> {
    throw new IOException("some io error");
});
// assert stuff here about the exception
We should add this to LuceneTestCase until junit5 is available.
Status:
RESOLVED
Priority:
Major
Resolution:
Fixed
Affects_version:
None
Fix_version:
6.0
Component:
None
Label:
None
Environment:

Attachment number:
0
Assignee:
Ryan Ernst
Reporter:
Ryan Ernst
Create date:
03/Feb/16 06:17
Update date:
09/May/16 18:32
Resolved date:
03/Feb/16 20:21
