Summary:
get_range_slices does not validate end_token
Description:
get_range_slices times out, java log has the following exception:
ERROR [Thrift:1] 2012-12-22 08:14:30,120 AbstractCassandraDaemon.java (line 135) Exception in thread Thread[Thrift:1,5,main]
java.lang.AssertionError: [DecoratedKey(28555413689034504124051437792156504, 6434313866653035643631663962323635323937343337653666636265616162),max(0)]
at org.apache.cassandra.dht.Bounds.<init>(Bounds.java:45)
at org.apache.cassandra.dht.Bounds.<init>(Bounds.java:38)
at org.apache.cassandra.thrift.CassandraServer.get_range_slices(CassandraServer.java:698)
at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3083)
at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3071)
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:186)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)
We see it every time on the SECOND get_range_slices call when we clear start_token and set start_key in the key range.
We noticed this in 1.1.7 first, 1.1.8 still affected. 1.1.6 is fine.
Please contact me if you need more information.
Status:
RESOLVED
Priority:
Low
Resolution:
Fixed
Affects_version:

Fix_version:
1.1.9, 1.2.0
Component:
None
Label:
None
Environment:

Attachment number:
0
Assignee:
Jonathan Ellis
Reporter:
Aleksey Pesternikov
Create date:
23/Dec/12 21:04
Update date:
16/Apr/19 09:32
Resolved date:
09/Jan/13 22:29
