Summary:
NPE in describe_ring
Description:
Not sure how much of the following is relevant besides the stack trace, but here I go:
I have a 2 DC, 2 node per DC cluster. DC1 had it's seed replaced but I hadn't restarted. I upgraded to 0.8.4 in the following fashion:
-edited seeds
-stopped both DC1 nodes
-upgraded jars
-started both nodes at the same time
The non-seed node came up first and showed the following error. Then when the seed node came up, the error went away on the non-seed node but started occurring on the seed node:
ERROR [pool-2-thread-15] 2011-08-12 22:32:27,438 Cassandra.java (line 3668) Internal error processing describe_ring
java.lang.NullPointerException
at org.apache.cassandra.service.StorageService.getRangeToRpcaddressMap(StorageService.java:623)
at org.apache.cassandra.thrift.CassandraServer.describe_ring(CassandraServer.java:731)
at org.apache.cassandra.thrift.Cassandra$Processor$describe_ring.process(Cassandra.java:3664)
at org.apache.cassandra.thrift.Brisk$Processor.process(Brisk.java:464)
at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:187)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:619)
Status:
RESOLVED
Priority:
Normal
Resolution:
Fixed
Affects_version:

Fix_version:
0.8.5
Component:
None
Label:
None
Environment:

Attachment number:
0
Assignee:
Brandon Williams
Reporter:
Eric Falcao
Create date:
12/Aug/11 22:47
Update date:
16/Apr/19 09:32
Resolved date:
24/Aug/11 16:11
