Summary:
php thrift's getRow() would throw an exception if the row does not exist
Description:
I've been played with thrift recently, and observed an unexpected behavior: when getRow() encounters an non-existent row key, it throws an exception like this:
PHP Fatal error: Uncaught exception 'Exception' with message 'getRow failed: unknown result' in pear/thrift/packages/Hbase/Hbase.php:715
Stack trace:
#0 pear/thrift/packages/Hbase/Hbase.php(666): HbaseClient->recv_getRow()
#1 htdocs/hbase/DemoClient.php(174): HbaseClient->getRow('demo_table', '00100-XXXX')
#2
{main}
thrown in pear/thrift/packages/Hbase/Hbase.php on line 715
I would expect when we pass a non-existent key, it can throw something like NotFound (as in scanner) or one can test with RowResult.isEmpty() just like in java api.
Status:
CLOSED
Priority:
Minor
Resolution:
Fixed
Affects_version:
0.19.0, 0.19.1
Fix_version:
0.19.2, 0.20.0
Component:
Thrift
Label:
None
Environment:

Attachment number:
0
Assignee:
Rong-En Fan
Reporter:
Rong-En Fan
Create date:
27/Mar/09 14:17
Update date:
13/Sep/09 22:24
Resolved date:
23/Apr/09 20:39
